---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80
  selector:
    app: web



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: httpd
        image: aaditya5/aadi:latest
        ports:
        - containerPort: 80
     
       
